### ISSUE TITLE
UseCase: TokenBalance substreams

### ISSUE THREAD

**Issue by jubeless** [streamingfast/substreams-sink-kv#13]
# TokenBalance (for all ERC20)

## Description

* For each user of each ERC20token, keep the latest balance
* A consumer would want to answer *these questions*
  * func userBalance(user, tokenContract) -> balance
  * func usersBalance(tokenContract) -> []{"bob": 123}
  * func userBalances(user) -> []{"weth": 123, "usdt": 456}
* (paginated using SCAN startKey= user:\0  endKey= user:\fffffffffffffff, limit:1000, then next page: startKey=(last received...)

**Comment by maoueh** [comment]
Closing in favor of #23
