### ISSUE TITLE
Improve CLI by including additional flags & default params for `run`

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams-sink-kv#4]
Would be nice if `substreams-sink-kv` could provide similar default params as `substreams run` CLI

**current**

```
substreams-sink-kv run <dsn> <endpoint> <manifest> <module> [<start>:<stop>]

$ substreams-sink-kv run badger3://badger_data.db mainnet.eth.streamingfast.io:443 substreams.yaml kv_out
```

**with defaults & flags**

```
substreams-sink-run <dsn> [<manifest>] [<module_name>] [<start>:<stop>] [flags]

$ substreams-sink-kv run badger3://badger_data.db
```

## Default params

- [x] manifest=`substreams.yaml` (similar to `substreams` CLI)
- [x] module=`kv_out`

## New flags

- [x] `-e, --substreams-endpoint string` (default = `mainnet.eth.streamingfast.io:443`)

**Comment by maoueh** [comment]
I introduced a regression while doing `2.1.0` where manifest is now required. I'll fix this tomorrow.

**Comment by maoueh** [comment]
Endpoint will be mandatory, I don't think it's a good idea to have a default here.

**Comment by maoueh** [comment]
`substreams-sink-kv inject <endpoint> <dsn>` is the minimal now. For this, the `substreams.yaml` must have a `sink` config defined.

`--module <name>` can be used when consuming "legacy" definition where no `sink` config exists.
